# Generated by Django 4.1.1 on 2022-09-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityModel',
            fields=[
                ('authority_id', models.AutoField(primary_key=True, serialize=False)),
                ('authority_name', models.CharField(help_text='authority_name', max_length=100)),
                ('contact_number', models.BigIntegerField(help_text='contact_number', null=True)),
                ('city', models.CharField(help_text='city', max_length=100)),
            ],
            options={
                'db_table': 'authority_details',
            },
        ),
    ]
