# Generated by Django 4.1.1 on 2022-09-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailsModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(help_text='mechanic_name', max_length=100)),
                ('user_email', models.CharField(help_text='mechanic_email', max_length=40)),
                ('user_number', models.BigIntegerField(help_text='mechanic_number', null=True)),
                ('user_city', models.CharField(help_text='mechanic_city', max_length=30)),
                ('user_password', models.CharField(help_text='mechanic_password', max_length=8)),
                ('user_pic', models.FileField(null=True, upload_to='images')),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
