# Generated by Django 4.1.1 on 2022-09-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookingModel',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(help_text='service_type', max_length=100)),
                ('vehicle_type', models.CharField(help_text='vehicle_type', max_length=40)),
                ('vehicle_number', models.CharField(help_text='vehicle_number', max_length=20)),
                ('booking_date', models.CharField(help_text='booking_date', max_length=20)),
                ('booking_time', models.CharField(help_text='booking_time', max_length=20, null=True)),
                ('user_problem', models.CharField(help_text='user_problem', max_length=200)),
            ],
            options={
                'db_table': 'user_booking_details',
            },
        ),
    ]
