# Generated by Django 4.1.1 on 2022-10-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_userbookingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookingmodel',
            name='latitude',
            field=models.CharField(help_text='latitude', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userbookingmodel',
            name='longitude',
            field=models.CharField(help_text='longitude', max_length=50, null=True),
        ),
    ]
