# Generated by Django 4.1.1 on 2022-10-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_userbookingmodel_latitude_userbookingmodel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookingmodel',
            name='status',
            field=models.CharField(default='Pending', help_text='status', max_length=10, null=True),
        ),
    ]
