# Generated by Django 4.1.1 on 2022-10-18 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicapp', '0007_mechanic_detailsmodel_date'),
        ('userapp', '0004_userbookingmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookingmodel',
            name='mechanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mechanicapp.mechanic_detailsmodel'),
        ),
    ]
