# Generated by Django 4.1.1 on 2022-10-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_userbookingmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='rating', max_length=100)),
                ('comment', models.CharField(help_text='comment', max_length=40)),
                ('sentiment', models.CharField(help_text='sentiment', max_length=80, null=True)),
            ],
            options={
                'db_table': 'feedback_details',
            },
        ),
    ]
