# Generated by Django 4.1.1 on 2022-10-18 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_feedbackmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.userbookingmodel'),
        ),
    ]
