# Generated by Django 4.1.1 on 2022-10-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_feedbackmodel_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='rating',
            field=models.IntegerField(help_text='rating'),
        ),
    ]
