# Generated by Django 4.1.1 on 2022-10-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicapp', '0008_mechanic_detailsmodel_average'),
        ('userapp', '0011_feedbackmodel_mechanic'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBooking2Model',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(help_text='service_type', max_length=100)),
                ('vehicle_type', models.CharField(help_text='vehicle_type', max_length=40)),
                ('vehicle_number', models.CharField(help_text='vehicle_number', max_length=20)),
                ('booking_date', models.CharField(help_text='booking_date', max_length=20)),
                ('booking_time', models.CharField(help_text='booking_time', max_length=20, null=True)),
                ('user_problem', models.CharField(help_text='user_problem', max_length=200)),
                ('status', models.CharField(default='Pending', help_text='status', max_length=10, null=True)),
                ('mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mechanicapp.mechanic_detailsmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.userdetailsmodel')),
            ],
            options={
                'db_table': 'user_bookings_details',
            },
        ),
    ]
