# Generated by Django 4.1.1 on 2022-10-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_userbooking2model'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userbooking2model',
            table='user_booking2_details',
        ),
    ]
