# Generated by Django 4.1.1 on 2022-10-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_alter_userbooking2model_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookingmodel',
            name='feedbackstatus',
            field=models.CharField(default='Pending', help_text='status', max_length=10, null=True),
        ),
    ]
