# Generated by Django 4.1.1 on 2022-10-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicapp', '0008_mechanic_detailsmodel_average'),
        ('userapp', '0014_userbookingmodel_feedbackstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBooking2Model',
            new_name='NormalbookingModel',
        ),
    ]
