# Generated by Django 4.1.1 on 2022-10-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_alter_normalbookingmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalbookingmodel',
            name='feedbackstatus',
            field=models.CharField(default='Pending', help_text='status', max_length=10, null=True),
        ),
    ]
