# Generated by Django 4.1.1 on 2022-10-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_normalbookingmodel_feedbackstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NormalbookingModel',
        ),
    ]
