# Generated by Django 4.1.1 on 2022-10-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_delete_normalbookingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookingmodel',
            name='booking_date',
            field=models.CharField(help_text='booking_date', max_length=20, null=True),
        ),
    ]
