# Generated by Django 4.1.1 on 2022-10-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_alter_userbookingmodel_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookingmodel',
            name='booking_type',
            field=models.CharField(help_text='booking_type', max_length=10, null=True),
        ),
    ]
