# Generated by Django 4.1.1 on 2022-11-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_userbookingmodel_remote_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookingmodel',
            name='booking_date',
            field=models.DateField(null=True),
        ),
    ]
