# Generated by Django 4.1.1 on 2022-11-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_alter_userbookingmodel_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookingmodel',
            name='booking_date',
            field=models.CharField(help_text='booking_date', max_length=20, null=True),
        ),
    ]
