# Generated by Django 4.1.1 on 2022-11-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0024_alter_userbookingmodel_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookingmodel',
            name='booking_date',
            field=models.DateField(auto_now_add=True, help_text='booking_date', max_length=20, null=True),
        ),
    ]
