# Generated by Django 4.1.1 on 2022-09-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicModel',
            fields=[
                ('mechanic_id', models.AutoField(primary_key=True, serialize=False)),
                ('mechanic_name', models.CharField(help_text='mechanic_name', max_length=100)),
                ('mechanic_email', models.CharField(help_text='mechanic_email', max_length=40)),
                ('mechanic_number', models.BigIntegerField(help_text='mechanic_number', null=True)),
                ('mechanic_city', models.CharField(help_text='mechanic_city', max_length=30)),
                ('mechanic_password', models.CharField(help_text='mechanic_password', max_length=8)),
                ('mechanic_pic', models.FileField(null=True, upload_to='documents/')),
            ],
            options={
                'db_table': 'mechanic_details',
            },
        ),
    ]
