# Generated by Django 4.1.1 on 2022-09-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MechanicModel',
            new_name='Mechanic_detailsModel',
        ),
    ]
