# Generated by Django 4.1.1 on 2022-10-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicapp', '0003_mechanic_shopmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic_detailsmodel',
            name='status',
            field=models.CharField(default='Pending', help_text='status', max_length=10, null=True),
        ),
    ]
