# Generated by Django 4.1.1 on 2022-10-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicapp', '0004_mechanic_detailsmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic_detailsmodel',
            name='status',
            field=models.CharField(default='Pending', help_text='status', max_length=15, null=True),
        ),
    ]
