# Generated by Django 4.1.1 on 2022-10-17 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicapp', '0005_alter_mechanic_detailsmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic_shopmodel',
            name='mechanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mechanicapp.mechanic_detailsmodel'),
        ),
    ]
