# Generated by Django 4.1.1 on 2022-10-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicapp', '0007_mechanic_detailsmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic_detailsmodel',
            name='average',
            field=models.IntegerField(help_text='average', null=True),
        ),
    ]
